language: generic
os: linux

cache:
  directories:
    - $HOME/.ccache

notifications:
  email:
    on_failure: always
    recipients:
      - a.gutenkunst@pilz.de
      - c.henkel@pilz.de
      - h.slusarek@pilz.de
      - i.martini@pilz.de
      - s.heinisch@pilz.de
      - c.doehn@pilz.de
      - g.sansone@pilz.de
      - r.feistenauer@pilz.de
env:
  global:
    - AFTER_SCRIPT='apt list --installed | grep "^ros-"'
    - CCACHE_DIR=$HOME/.ccache
    - ROS_DISTRO="melodic"
    - CATKIN_LINT=true
    - CATKIN_LINT_ARGS='--strict'

jobs:
  include:
    # Main Job - Checks against released packages
    - name: "Build + Test with Main Repo (http://packages.ros.org/ros/ubuntu)"
      install:
        - git clone --depth=1 --branch master https://github.com/ros-industrial/industrial_ci.git .industrial_ci
      env:
        - ROS_REPO=main
      script:
        - .industrial_ci/travis.sh
